@startuml
'https://plantuml.com/class-diagram

interface ITokenize {
   List<String> tokenize()
}
class TachTu {
    - String str
}
class TokenDecorator {
}
class LoaiBoTuDung {
    - List<String> tuDungs
}
class LoaiBoDauCau

ITokenize <|... TokenDecorator
ITokenize <|... TachTu
ITokenize <-- TokenDecorator: token

TokenDecorator <|-- LoaiBoTuDung
TokenDecorator <|-- LoaiBoDauCau

@enduml