@startuml
'https://plantuml.com/class-diagram

abstract class ImageProcess {
    + void process()
}

class BasicProcess {
    - String path
}

class ImageDecorator {
    # String value
}

class BorderDecorator
class WatermarkDecorator
class FilterDecorator

ImageProcess <|-- ImageDecorator
ImageProcess <|-- BasicProcess

ImageDecorator <|-- BorderDecorator
ImageDecorator <|-- WatermarkDecorator
ImageDecorator <|-- FilterDecorator

ImageProcess <--- ImageDecorator: image

@enduml