@startuml
'https://plantuml.com/class-diagram

class Book
{
    - String title, author
    - int pages
    - List<String> chapters
    # Book(Builder b)
}

class Builder {
    + Builder buildBook(String title, String author, int pages, List<String> chapters)
    + Book build()
}

Builder ..> Book

@enduml