@startuml
'https://plantuml.com/class-diagram

abstract class Node {
    - int val
    + {abstract} void iterate()
    + {abstract} void addLeft(Node n)
    + {abstract} void addRight(Node n)
}

class LeafNode
class ParentNode

'nút lá ke thua giao diện nút
Node <|-- LeafNode

'nút trong ke thua thực thi giao diện nút
Node <|-- ParentNode

ParentNode --> Node: "Left"
ParentNode --> Node: "Right"

@enduml