@startuml
'https://plantuml.com/class-diagram

class GioHang {
    + void thanhToan();
}

interface IThanhToan {
    float thanhToan(float soTien)
}

class COD
class AirPlay

interface IKhuyenMai {
    float thanhToan(float soTien)
}

class KhuyenMai_10_Max100

class MatHang {
    - String ten
    - float gia
    - int sl
}

IThanhToan <|.. COD
IThanhToan <|.. AirPlay
IKhuyenMai <|.. KhuyenMai_10_Max100
MatHang <--* GioHang: dsmh
IKhuyenMai <-- GioHang: km
IThanhToan <-- GioHang: httt

@enduml