@startuml
'https://plantuml.com/class-diagram

class Atm {
    - int innerTien
    + void setState(AtmState state)
    + void rutTien(int soTien)
    + void napTien(int soTien)
}

interface AtmState {
    void handleRutTien(int soTien, Atm atm)
    void handleNapTien(int soTien, Atm atm)
}

class SanSangState
class HanCheState
class HetTienState

Atm --> AtmState: state
AtmState <|.. SanSangState
AtmState <|.. HanCheState
AtmState <|.. HetTienState

@enduml